### ISSUE TITLE
抢了两次都是抢购失败呢，获取成员和医院都没有问题

### ISSUE THREAD

**Issue by 19961102** [lyrric/seckill#10]

**Comment by lyrric** [comment]
多开几个程序，多用几个号，多用几个电脑
黄牛党都是十多个微信号，几台电脑同时抢的
所以要拼几率，我是抢购成功过的

**Comment by 19961102** [comment]
我看了下代码是超过时间就提示抢购失败，大佬可以换成我的-我的预约那个界面查看是否有订单

**Comment by lyrric** [comment]
> 我看了下代码是超过时间就提示抢购失败，大佬可以换成我的-我的预约那个界面查看是否有订单

那样做是无用操作，其实往往一两秒，秒杀就已经结束了

提示失败基本能就是失败了（极少情况会出现成功了，提示失败）
秒杀成功了那就是一定成功了

**Comment by lyrric** [comment]
另外，保证电脑时间与互联网时间一致，也是一个很重要的因素

**Comment by MatchOfLin** [comment]
> 另外，保证电脑时间与互联网时间一致，也是一个很重要的因素
正常情况下都是保持一致的吧。默认是跟随网络

**Comment by lyrric** [comment]
> > 另外，保证电脑时间与互联网时间一致，也是一个很重要的因素
> > 正常情况下都是保持一致的吧。默认是跟随网络

不一定，检查一下最好

**Comment by 19961102** [comment]
又试了一次，时间提前同步后，看日志8：59：59开始秒杀，然后一直报未知异常，百分之九十九报的都是未知异常，然后就是报抢购失败，频繁

**Comment by Maxmumu** [comment]
> 又试了一次，时间提前同步后，看日志8：59：59开始秒杀，然后一直报未知异常，百分之九十九报的都是未知异常，然后就是报抢购失败，频繁

我第一次尝试，失败
![image](https://user-images.githubusercontent.com/47938014/89964486-d83aa980-dc7c-11ea-8327-f27b841a48b8.png)

**Comment by Maxmumu** [comment]
> 多开几个程序，多用几个号，多用几个电脑
> 黄牛党都是十多个微信号，几台电脑同时抢的
> 所以要拼几率，我是抢购成功过的

1.一个电脑怎么多开呢
2.不同微信号登录小程序，绑定同一个人，这样抢可以吗
3.一个微信的tk和Cookie可以多个程序用吗

**Comment by lyrric** [comment]
> > 多开几个程序，多用几个号，多用几个电脑
> > 黄牛党都是十多个微信号，几台电脑同时抢的
> > 所以要拼几率，我是抢购成功过的
> 
> 1.一个电脑怎么多开呢
> 2.不同微信号登录小程序，绑定同一个人，这样抢可以吗
> 3.一个微信的tk和Cookie可以多个程序用吗

可以的
今天上午九点的，我也成功帮我朋友秒杀了一个
我用了两个微信号，同时启动了四个程序，一个号在两个程序上跑

**Comment by lyrric** [comment]
> 又试了一次，时间提前同步后，看日志8：59：59开始秒杀，然后一直报未知异常，百分之九十九报的都是未知异常，然后就是报抢购失败，频繁

不能保证百分百成功，但是成功几率还是挺大
多开几个程序，多试几次，总会抢到一次的
![TIM截图20200812094500](https://user-images.githubusercontent.com/20310859/89965919-8d229580-dc80-11ea-9521-86cea4ea7e3c.jpg)

**Comment by Maxmumu** [comment]
> > > 多开几个程序，多用几个号，多用几个电脑
> > > 黄牛党都是十多个微信号，几台电脑同时抢的
> > > 所以要拼几率，我是抢购成功过的
> > 
> > 
> > 1.一个电脑怎么多开呢
> > 2.不同微信号登录小程序，绑定同一个人，这样抢可以吗
> > 3.一个微信的tk和Cookie可以多个程序用吗
> 
> 可以的
> 今天上午九点的，我也成功帮我朋友秒杀了一个
> 我用了两个微信号，同时启动了四个程序，一个号在两个程序上跑

一个电脑怎样多开程序呢

**Comment by lyrric** [comment]
> > > > 多开几个程序，多用几个号，多用几个电脑
> > > > 黄牛党都是十多个微信号，几台电脑同时抢的
> > > > 所以要拼几率，我是抢购成功过的
> > > 
> > > 
> > > 1.一个电脑怎么多开呢
> > > 2.不同微信号登录小程序，绑定同一个人，这样抢可以吗
> > > 3.一个微信的tk和Cookie可以多个程序用吗
> > 
> > 
> > 可以的
> > 今天上午九点的，我也成功帮我朋友秒杀了一个
> > 我用了两个微信号，同时启动了四个程序，一个号在两个程序上跑
> 
> 一个电脑怎样多开程序呢

怎么打开的，就怎么多开
