### ISSUE TITLE
知苗可以手机和电脑同时登陆吗？今天程序提示获取st失败：用户登录超时，请重新登入

### ISSUE THREAD

**Issue by UESTCrookieLI** [lyrric/seckill#106]
![图片](https://user-images.githubusercontent.com/55549767/130710206-e18a1a94-95b9-460f-be91-0749c43804cb.png)

所以现在有个疑问知苗可以手机和电脑同时登陆吗？

**Comment by qiyunzhou** [comment]
不能，用pc微信就不要登录手机了

**Comment by ibrahidy** [comment]
> 不能，用pc微信就不要登录手机了

PC微信和手机不是同时在线的吗？是电脑抢就不能用手机抢吗？

**Comment by qiyunzhou** [comment]
> > 不能，用pc微信就不要登录手机了
> 
> PC微信和手机不是同时在线的吗？是电脑抢就不能用手机抢吗？
> 是的

**Comment by wlinnilw** [comment]
但是现在你手机退出登录，电脑也直接下线了啊

**Comment by qiyunzhou** [comment]
没有呀，电脑版微信打开小程序就好了，手机别动就行了。你怎么操作的？
