### ISSUE TITLE
关于医保区划

### ISSUE THREAD

**Issue by MatchOfLin** [lyrric/seckill#11]
在里面看得到使用了成都的医保区划，用成都是可以查得到医院的。
为什么换了其他城市的医保区划就不行了呢。比如武汉和北京等等，我在武汉的某个医院可以手动搜索和预约，但是用您的秒杀却找不到。
在我的理解里，修改了其他城市的医保区划的前四位就可以了吧。

**Comment by lyrric** [comment]
> 在里面看得到使用了成都的医保区划，用成都是可以查得到医院的。
> 为什么换了其他城市的医保区划就不行了呢。比如武汉和北京等等，我在武汉的某个医院可以手动搜索和预约，但是用您的秒杀却找不到。
> 在我的理解里，修改了其他城市的医保区划的前四位就可以了吧。

这个是约苗小程序的脚本，我看了下约苗里面北京和武汉目前是没有疫苗的，所以在我的程序里面没有是正常的
