### ISSUE TITLE
老哥V587，作为前端的我也想写这么一个，无奈自己技术有限，谢谢老哥，经过几次尝试，我终于抢到了，谢谢

### ISSUE THREAD

**Issue by lzming1989** [lyrric/seckill#12]

**Comment by Maxmumu** [comment]
几台电脑，开了几个程序，网络环境怎么样，求分享经验

**Comment by lyrric** [comment]
哈哈，还有那么多老哥都没抢到

**Comment by lzming1989** [comment]
> 哈哈，还有那么多老哥都没抢到

我也是这用这个程序抢了很多次了

**Comment by lzming1989** [comment]
> 几台电脑，开了几个程序，网络环境怎么样，求分享经验

一台电脑，双开，网络时间还有1秒的时候点开始，无其他经验

**Comment by lzming1989** [comment]
13:33:23.363  INFO   com.github.lyrric.Main  17 main ==>  =================程序开始运行=================
13:59:58.673  INFO   com.github.lyrric.service.SecKillService  73 startSecKill ==>  还未到开始时间，等待中......
13:59:59.800  INFO   com.github.lyrric.service.SecKillService  82 startSecKill ==>  ###########第一波 开始秒杀###########
13:59:59.980  INFO   com.github.lyrric.service.SecKillService  91 startSecKill ==>  ###########第二波 开始秒杀###########
14:00:03.189  INFO   com.github.lyrric.service.SecKillService  82 startSecKill ==>  ###########第一波 开始秒杀###########
14:00:03.541  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:03.560  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:03.638  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:03.644  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:03.644  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:03.727  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:03.729  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:03.730  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:03.745  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:03.746  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:03.849  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:03.914  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:03.992  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:03.993  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:04.102  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:04.232  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:04.514  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:04.525  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:05.170  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:05.180  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:05.190  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:05.199  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:05.252  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:05.269  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:05.291  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:05.366  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:05.399  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:05.406  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:05.417  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:05.423  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:05.495  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 该账号已秒杀过HPV疫苗，请勿重复秒杀
14:00:05.500  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:05.604  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:05.646  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:05.697  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:05.752  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:06.257  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 该账号已秒杀过HPV疫苗，请勿重复秒杀
14:00:07.983  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:07.983  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:07.983  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 该账号已秒杀过HPV疫苗，请勿重复秒杀
14:00:07.984  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:07.984  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:08.041  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:08.201  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 排队人数较多,请耐心等待!
14:00:09.193  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:10.889  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:10.972  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:11.334  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:17.428  INFO   com.github.lyrric.service.SecKillService  60 lambda$startSecKill$0 ==>  抢购失败: 操作过于频繁,请稍后再试!
14:00:17.431  INFO   com.github.lyrric.service.SecKillService  103 startSecKill ==>  抢购成功，请登录约苗小程序查看
