### ISSUE TITLE
又一次陪跑。好难

### ISSUE THREAD

**Issue by xl-0827** [lyrric/seckill#130]
15:00:00.571  WARN   com.github.lyrric.service.SecKillService  56 startSecKill ==>  httpService.log,未知异常:null，
15:00:00.571  INFO   com.github.lyrric.service.HttpService  171 getCommonHeader ==>  cookie is tgw_l7_route=187db25810c347ee780c442da2b2a23c; _xzkj_=wxapptoken:10:87493e65a51f3fd17eddc3296399863f_896bcd71a9454221272d0e569de2b039
15:00:12.515  INFO   com.github.lyrric.service.SecKillService  64 startSecKill ==>  Thread ID：22，发送请求
15:00:12.516  INFO   com.github.lyrric.service.HttpService  171 getCommonHeader ==>  cookie is tgw_l7_route=187db25810c347ee780c442da2b2a23c; _xzkj_=wxapptoken:10:87493e65a51f3fd17eddc3296399863f_896bcd71a9454221272d0e569de2b039
15:01:19.686  WARN   com.github.lyrric.service.SecKillService  79 startSecKill ==>  Thread ID: 22，未知异常

全部是发送请求，未知异常，这是什么原因?

**Comment by lzy951014** [comment]
你咋关闭了？

**Comment by xl-0827** [comment]
> 你咋关闭了？

我在之前别人发的提问里看到问题了
