### ISSUE TITLE
问下大佬们，我抓包了Cookie和tk，选择成员的时候还是提示用户登录超时

### ISSUE THREAD

**Issue by hcy122147726** [lyrric/seckill#145]
之前一直抓包可以的，这几次都是选择用户的时候超时

**Comment by hcy122147726** [comment]
![Uploading QQ图片20210924141501.png…]()

**Comment by hcy122147726** [comment]
![QQ图片20210924141501](https://user-images.githubusercontent.com/51126284/134627353-82c7d1bd-f774-434e-8fb6-551a10cd257d.png)

**Comment by ying9512** [comment]
我正常抓没问题，把你抓的放出来看看
