### ISSUE TITLE
请问其他的地方可以抢嘛？

### ISSUE THREAD

**Issue by MatchOfLin** [lyrric/seckill#15]
请问其他的地方可以抢嘛？

**Comment by choucmei** [comment]
都可以，进入小程序的时候，选择地区后。抓包 有个请求是 regionCode 或者 反编 小程序，然后改com.github.lyrric.service.HttpService#getVaccineList 的regionCode 即可

**Comment by MatchOfLin** [comment]
> 都可以，进入小程序的时候，选择地区后。抓包 有个请求是 regionCode 或者 反编 小程序，然后改com.github.lyrric.service.HttpService#getVaccineList 的regionCode 即可

你有试过吗，我换成其他城市的医保区划时找不到。

**Comment by choucmei** [comment]
试过啊，你是哪个地方来着

**Comment by choucmei** [comment]
> > 都可以，进入小程序的时候，选择地区后。抓包 有个请求是 regionCode 或者 反编 小程序，然后改com.github.lyrric.service.HttpService#getVaccineList 的regionCode 即可
> 
> 你有试过吗，我换成其他城市的医保区划时找不到。

试过啊，你是哪个地方来着

**Comment by MatchOfLin** [comment]
> > > 都可以，进入小程序的时候，选择地区后。抓包 有个请求是 regionCode 或者 反编 小程序，然后改com.github.lyrric.service.HttpService#getVaccineList 的regionCode 即可
> > 
> > 
> > 你有试过吗，我换成其他城市的医保区划时找不到。
> 
> 试过啊，你是哪个地方来着

长沙，我也对武汉，北京等多个城市也查过，是我查的时间不合适嘛。

**Comment by MatchOfLin** [comment]
> > > 都可以，进入小程序的时候，选择地区后。抓包 有个请求是 regionCode 或者 反编 小程序，然后改com.github.lyrric.service.HttpService#getVaccineList 的regionCode 即可
> > 
> > 
> > 你有试过吗，我换成其他城市的医保区划时找不到。
> 
> 试过啊，你是哪个地方来着

问一下您抢过哪个城市呢

**Comment by choucmei** [comment]
之前有帮我妹妹抢过无锡的

MatchOfLin <notifications@github.com> 于2020年8月17日周一 下午6:26写道：
