### ISSUE TITLE
抢的频率过高会提示操作频繁被封禁一段时间吗？

### ISSUE THREAD

**Issue by luolongfei** [lyrric/seckill#18]
我正打算用python实现同样的功能，目前还没抢过，不清楚会不会有被封禁的情况，要是没封禁的话我打算把线程弄多一些

**Comment by lyrric** [comment]
不会，放心搞

**Comment by w535339337** [comment]
您好，能不能加一个广西南宁地区，帮我女朋友抢的，我昵称是我扣抠，谢谢了

**Comment by lyrric** [comment]
> 您好，能不能加一个广西南宁地区，帮我女朋友抢的，我昵称是我扣抠，谢谢了

广西南宁并没有看到有秒杀活动

**Comment by luolongfei** [comment]
早上开了666个线程，到后面我看返回的错误是操作频繁，不过早上可能是我电脑时间延迟的问题，我看了http://time.is我电脑慢了1.3s，下次再试试

**Comment by w535339337** [comment]
> > 您好，能不能加一个广西南宁地区，帮我女朋友抢的，我昵称是我扣抠，谢谢了
> 
> 广西南宁并没有看到有秒杀活动

今早有，现在好像结束了

**Comment by w535339337** [comment]
是要有秒杀活动的时候才能写吗

**Comment by w535339337** [comment]
我朋友说把("regionCode","5101");，这个地区代码改成南宁的4501，应该就可以

**Comment by lyrric** [comment]
> > > 您好，能不能加一个广西南宁地区，帮我女朋友抢的，我昵称是我扣抠，谢谢了
> > 
> > 
> > 广西南宁并没有看到有秒杀活动
> 
> 今早有，现在好像结束了

也不是，只是确认下，有些地区是一直都没有秒杀活动的
后面我简单弄下选择地区的功能

**Comment by w535339337** [comment]
期待你的更新

**Comment by lyrric** [comment]
> 我朋友说把("regionCode","5101");，这个地区代码改成南宁的4501，应该就可以

是可以，你要是会一点编程基础的话，可以自己搞定

**Comment by lyrric** [comment]
> 期待你的更新

release v1.2加入了地区选择功能
