### ISSUE TITLE
关于登录超时问题的一个总结

### ISSUE THREAD

**Issue by Stepend** [lyrric/seckill#181]
今天下午搞了一下午，从一篇http://the7.net/news/show-15535.html博客过来，老是显示登陆超时。
这个问题的原因是因为在打开秒苗时抓取到的包不带有个人登录信息，所以老是失败。
解决方案是：
       进入秒苗小程序后，点击预约的诊所进行抓包，此时复制Cookie和tk到文本框相应位置，点击解析即可。

**Comment by Huangqihao123** [comment]
一般登录超时都是token或者cookie过期，抢疫苗前5分钟抓包启动程序应该不会出现这种问题

**Comment by Stepend** [comment]
进去后抓包就不会出现，但是貌似后台做了手脚，不然黄牛不可能这么猖獗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月8日(星期三) 中午11:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [lyrric/seckill] 关于登录超时问题的一个总结 (Issue #181)





 
一般登录超时都是token或者cookie过期，抢疫苗前5分钟抓包启动程序应该不会出现这种问题
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
