### ISSUE TITLE
下次把秒杀时间改为提前两秒，也许成功率会高些

### ISSUE THREAD

**Issue by lyrric** [lyrric/seckill#20]
通过观察日志，发现第一个请求发送与13:59:59.834，但是第一个回复时间却是14:00:02.804，并提示排队人数较多,请耐心等待!
猜测之前的请求都被加入了队列等候处理，导致抢购几率下降

**Comment by luolongfei** [comment]
建议将开始时间或者提前时间做成自定义，因为每个人的系统时间也许会有差异，而且也不能设置到毫秒级别的一致

**Comment by luolongfei** [comment]
提前后会直接提示操作频繁
