### ISSUE TITLE
现在没法获取到tk了，你们的是吗

### ISSUE THREAD

**Issue by zhq1** [lyrric/seckill#208]

**Comment by yang-shengbo** [comment]
你用的知苗还是秒苗

**Comment by zhq1** [comment]
@yang-shengbo 知苗

**Comment by yang-shengbo** [comment]
@zhq1 我用知苗一直没有看到过tk参数 只有秒苗有  你以前在知苗有？是要进行转换吗

**Comment by zhq1** [comment]
@yang-shengbo 没有，我今天第一次用，帮亲戚抢个苗，知苗上面没法抓取tk是没办法用么，秒苗上面我刚测了好像能有tk但是没有看到有抢购信息

**Comment by yang-shengbo** [comment]
@zhq1 知苗上确实没有tk 我也是获取不到 秒苗也是和你一样的情况  太难了

**Comment by Laihaowen** [comment]
在git上都找不到能用的新的了

**Comment by zhq1** [comment]
@yang-shengbo 太难了

**Comment by Lazyrunner2020** [comment]
完犊子 黄牛太凶了

**Comment by Iprotagonist** [comment]
知苗好像没有tk，只有一个cookie吧
