### ISSUE TITLE
您好，请问选择直辖城市的时候，提示报错。

### ISSUE THREAD

**Issue by yxx5508** [lyrric/seckill#25]
![微信截图_20201118164858](https://user-images.githubusercontent.com/57649819/99507616-92e5f080-29be-11eb-92b8-7f1caf30bb62.png)

**Comment by lyrric** [comment]
能说说你的操作步骤吗？

**Comment by yxx5508** [comment]
> 能说说你的操作步骤吗？

谢谢您的回复，因为真的是小白的原因，摸索了很长时间。抓取cookie及tk 也按照设置里面复制了需要的字段并尝试很多方法，在不解析的情况下依旧能够获取到成员列表，并选择成功。然后选择城市，发现只有直辖市选择确定后，点击刷新疫苗列表报图片错误。其他城市，均无任何提示，默认无疫苗。然后我试图改了下直辖市的java文件中的数值，随意更改，抱着试一试的态度，然后发现刷新疫苗列表就不提示错误了。跟选择其他城市一样没有报错，默认状态吧。基本操作也就这些了，云里雾里的操作到现在。就打开图片中的界面都用了好久，苦笑。或者希望浪费您的短暂时间，录制一下简单的操作说明，必将十分感谢！

**Comment by lyrric** [comment]
这个问题解决了，v1.31版本。
直辖市的code有误，其他地区还是正常的，只是没有疫苗信息

**Comment by yxx5508** [comment]
十分感谢！

发送自 Windows 10 版邮件应用

发件人: lyrric
发送时间: 2020年11月23日 13:40
收件人: lyrric/seckill
抄送: yxx5508; Author
主题: Re: [lyrric/seckill] 您好，请问选择直辖城市的时候，提示报错。 (#25)

这个问题解决了，v1.31版本。
直辖市的code有误，其他地区还是正常的，只是没有疫苗信息
