### ISSUE TITLE
不知道FD里面哪个才是抓的小程序的包，miaomiao开头的吗，好绝望

### ISSUE THREAD

**Issue by dasiy997** [lyrric/seckill#26]

**Comment by lyrric** [comment]
里面有歌字段是tk:wxapptoken的

**Comment by dasiy997** [comment]
> 里面有歌弦是tk：wxapptoken的

OK大佬，我现在开始前一小时配置然后点击开始按钮，到了时间点他会自动开始吗

**Comment by lyrric** [comment]
尽量在一个小时内，不然cookie可能会过期
还有要保证系统当前时间准确

**Comment by dasiy997** [comment]
> 尽量在一个小时内，不然cookie可能会过期
> 还有要保证系统当前时间准确

大佬，试了下抢今天的，为什么提前点了开始，日记没有显示开始运行秒杀呢==都设置好了呀

**Comment by lyrric** [comment]
> > 尽量在一个小时内，不然cookie可能会过期
> > 还有要保证系统当前时间准确
> 
> 大佬，试了下抢今天的，为什么提前点了开始，日记没有显示开始运行秒杀呢==都设置好了呀

你说的日记是界面上的还是输出的log文件？
界面的有点bug，有时候不会显示信息，但实际流程是在运行的

**Comment by ZuWard** [comment]
FD里是不是抓不到云开发的tk了呀

**Comment by abserari** [comment]
是啊, 感觉没抓到

**Comment by lyndon12** [comment]
有没有抓到tk 。怎么抓都没有啊啊啊

**Comment by ltCodeW** [comment]
求问，今天没有放苗，想先试一试抓包。但是header字段里面没有tk字段，请教大佬，该怎么搞一下呢？
![图片](https://user-images.githubusercontent.com/41608419/103653125-065bb580-4f9f-11eb-852e-65ad77087194.png)

**Comment by lyrric** [comment]
> 求问，今天没有放苗，想先试一试抓包。但是header字段里面没有tk字段，请教大佬，该怎么搞一下呢？
> ![图片](https://user-images.githubusercontent.com/41608419/103653125-065bb580-4f9f-11eb-852e-65ad77087194.png)

抓包失败了，https没有抓成功
