### ISSUE TITLE
在秒杀时，发了几个请求就一直在控制台报错，然后卡死了，这是什么情况

### ISSUE THREAD

**Issue by canguser** [lyrric/seckill#27]
rt

**Comment by lyrric** [comment]
报错正常，服务器nginx撑不住经常挂
过了一分半如果还没抢到就不会抢了
卡死了是什么意思？log日志也没有打印？

**Comment by canguser** [comment]
可能是我并发脚本个数开得太多了，导致卡死了，对了，这个是不是不能和手机上小程序手动一起抢，发现小程序上抢会导致脚本挂的登录超时

**Comment by lyrric** [comment]
> 可能是我并发脚本个数开得太多了，导致卡死了，对了，这个是不是不能和手机上小程序手动一起抢，发现小程序上抢会导致脚本挂的登录超时

pc和移动端，一方登录了约苗，另一方的cookie和tk就会失效
