### ISSUE TITLE
发现新问题

### ISSUE THREAD

**Issue by 0728xjf** [lyrric/seckill#3]
我前几天运行代码的时候，可以看到成都有一家门诊6号上午9点可以抢，今天登进去，刷新疫苗列表的时候，日志记录写的是null，errCoden。其他设置没问题，cookie，选择成员也没问题。{"timestamp":"2020-08-04 12:17:36","status":404,"error":"Not Found","message":"No message available","path":"/department/pageList.do"}

**Comment by lyrric** [comment]
刚刚看了下，约苗的秒杀功能转到小程序了

**Comment by lzming1989** [comment]
> 刚刚看了下，约苗的秒杀功能转到小程序了

大早上很早来了公司就准备抢，结果迁移到小程序了，绝望

**Comment by SCULitao** [comment]
非常绝望

**Comment by lyrric** [comment]
小程序版已经在做了，接口基本理清了，目前在调试中。
但是小程序抓包比较麻烦，需要一定的门槛（比之前公众号的抓包要复杂的多）

**Comment by SCULitao** [comment]
> 刚刚看了下，约苗的秒杀功能转到小程序了

是的，小程序的链接都变了，我点预定都没抓到对应的url

**Comment by SCULitao** [comment]
> 小程序版已经在做了，接口基本理清了，目前在调试中。
> 但是小程序抓包比较麻烦，需要一定的门槛（比之前公众号的抓包要复杂的多）

可以用Charles抓包，您有发现提交请求的url吗，求分享，谢谢，wechat：litaodeng

**Comment by 0728xjf** [comment]
另外，提一点，小程序抓包的话，pc端和客户端都可以呀。现在微信PC端也是有小程序的了。

**Comment by lyrric** [comment]
> 另外，提一点，小程序抓包的话，pc端和客户端都可以呀。现在微信PC端也是有小程序的了。

我这边试过，发现无法直接抓包（用的fiddler）
你是试的约苗的小程序吗？用的什么工具

**Comment by lyrric** [comment]
> > 小程序版已经在做了，接口基本理清了，目前在调试中。
> > 但是小程序抓包比较麻烦，需要一定的门槛（比之前公众号的抓包要复杂的多）
> 
> 可以用Charles抓包，您有发现提交请求的url吗，求分享，谢谢，wechat：litaodeng

我这边是把小程序反编译了，找到的请求接口
关于小程序的反编译，网上教程还是比较多
嫌麻烦的话，可以看我的dev分支，里面接口基本已经写好了

**Comment by 0728xjf** [comment]
> > 另外，提一点，小程序抓包的话，pc端和客户端都可以呀。现在微信PC端也是有小程序的了。
> 
> 我这边试过，发现无法直接抓包（用的fiddler）
> 你是试的约苗的小程序吗？用的什么工具

我也是用的fiddler，确实没看到。
https://www.52pojie.cn/thread-1145984-1-1.html
这个教程大佬要不试一下，看看能否有用？

**Comment by lyrric** [comment]
> > > 另外，提一点，小程序抓包的话，pc端和客户端都可以呀。现在微信PC端也是有小程序的了。
> > 
> > 
> > 我这边试过，发现无法直接抓包（用的fiddler）
> > 你是试的约苗的小程序吗？用的什么工具
> 
> 我也是用的fiddler，确实没看到。
> https://www.52pojie.cn/thread-1145984-1-1.html
> 这个教程大佬要不试一下，看看能否有用？

小程序的抓包，我已经用夜神模拟器（root），XposedInstaller_3.1.5，JustTrustMe成功实现抓包了，具体使用比较简单，需要的可以去了解下

**Comment by 0728xjf** [comment]
> > > > 另外，提一点，小程序抓包的话，pc端和客户端都可以呀。现在微信PC端也是有小程序的了。
> > > 
> > > 
> > > 我这边试过，发现无法直接抓包（用的fiddler）
> > > 你是试的约苗的小程序吗？用的什么工具
> > 
> > 
> > 我也是用的fiddler，确实没看到。
> > https://www.52pojie.cn/thread-1145984-1-1.html
> > 这个教程大佬要不试一下，看看能否有用？
> 
> 小程序的抓包，我已经用夜神模拟器（root），XposedInstaller_3.1.5，JustTrustMe成功实现抓包了，具体使用比较简单，需要的可以去了解下

似乎Burpsuite可以抓电脑微信客户端的小程序包呀，这样的话岂不是不需要用到手机啦？
具体看这个20天前的教程：https://blog.csdn.net/u012206617/article/details/107366841

**Comment by SCULitao** [comment]
> > > > 另外，提一点，小程序抓包的话，pc端和客户端都可以呀。现在微信PC端也是有小程序的了。
> > > 
> > > 
> > > 我这边试过，发现无法直接抓包（用的fiddler）
> > > 你是试的约苗的小程序吗？用的什么工具
> > 
> > 
> > 我也是用的fiddler，确实没看到。
> > https://www.52pojie.cn/thread-1145984-1-1.html
> > 这个教程大佬要不试一下，看看能否有用？
> 
> 小程序的抓包，我已经用夜神模拟器（root），XposedInstaller_3.1.5，JustTrustMe成功实现抓包了，具体使用比较简单，需要的可以去了解下

如果是mac电脑，也可以用Charles + 微信最新Beta版本（电脑可以直接打开小程序）

**Comment by SCULitao** [comment]
![image](https://user-images.githubusercontent.com/34415874/89502907-5409a180-d7f8-11ea-9163-c00c7c7f8225.png)

**Comment by SCULitao** [comment]
![image](https://user-images.githubusercontent.com/34415874/89502987-78fe1480-d7f8-11ea-921f-5a3081082fcb.png)

**Comment by SCULitao** [comment]
现在提交订单没有验证码了，直接用这个url，直接简化了

**Comment by SCULitao** [comment]
![image](https://user-images.githubusercontent.com/34415874/89503212-cf6b5300-d7f8-11ea-8f4e-c6829cba8119.png)

**Comment by lyrric** [comment]
小程序V0.9版本已合入master分支
