### ISSUE TITLE
大佬 这个是怎么运行的呢 我下载下来用开发工具都打不开

### ISSUE THREAD

**Issue by xiaogewujiu** [lyrric/seckill#30]
大佬 这个是怎么运行的呢 我下载下来用开发工具都打不开

**Comment by lyrric** [comment]
https://pan.baidu.com/s/1vBh2zA8L5eTJ5fQs7LPbFA      密码：b8su

下载后安装环境
然后才能打开程序

**Comment by xzshen071** [comment]
大佬，我编译Main.java报找不到程序包的错误咋整。

类似这样：
Main.java:3: 错误: 程序包com.github.lyrric.ui不存在
import com.github.lyrric.ui.ConsoleMode;

**Comment by lyrric** [comment]
> 大佬，我编译Main.java报找不到程序包的错误咋整。
> 
> 类似这样：
> Main.java:3: 错误: 程序包com.github.lyrric.ui不存在
> import com.github.lyrric.ui.ConsoleMode;

编译是要整个项目一起编译的，编译单个文件不行
用idea或者maven来编译
