### ISSUE TITLE
抢了3次了，都没抢到，难搞

### ISSUE THREAD

**Issue by lorijlh** [lyrric/seckill#32]
第一次直接运行，没抢到，第二次加了伪IP，也没啥用，发现提前秒会报频繁提示，估计进小黑屋了。第三次直接上腾讯云服务器，开了150M带宽，因为看到他们家服务是广州腾讯云的服务地址，然后把线程直接集中在20ms的时候，还是没抢到，下波准备试试200M带宽，提前50ms，作者代码是写的很好的，程序方面应该是不存在问题了，感觉主要还是时间差以及硬件方面的问题

**Comment by lyrric** [comment]
试试多个微信号，因为判断不了频繁是根据账号还是ip，或者两者结合
