### ISSUE TITLE
选择成员这里总是提示登陆超时

### ISSUE THREAD

**Issue by CQ-HC** [lyrric/seckill#37]
在设置好tk和cookies后点击选择成员总是报登录超时的问题：
我抓取的tk和cookies如下：
Cookie: _xxhm_=%7B%22headerImg%22%3A%22http%3A%2F%2Fthirdwx.qlogo.cn%2Fmmopen%2FxjC97SLpMq2jKgwglpvG34HlCvQhJovrrKsvgmPqTPWohvia3nQGXrNIMIfyOQyiavYkiaLicnSWNrgRlh0yDn795icZTmmFxuRxK%2F132%22%2C%22mobile%22%3A%22181****3753%22%2C%22nickName%22%3A%22Kylin%22%2C%22sex%22%3A2%7D; _xzkj_=wxapptoken:10:9e5043c02c19a51164831be3791d98ae_243de0a7896767439ef696ffcc7b0225; d39f=ad889541eac3199bf4; eee8=5d151ba7b1708ceaae

tk: wxapptoken:10:9e5043c02c19a51164831be3791d98ae_243de0a7896767439ef696ffcc7b0225

把上面获取的两个字段在设置cookie界面填入；

![image](https://user-images.githubusercontent.com/33709498/102689612-7269ba00-423a-11eb-8e58-661b4cafc176.png)

**Comment by jakcky** [comment]
加QQ一起研究吗？？

**Comment by lyndon12** [comment]
> 加QQ一起研究吗？？

你qq好多呢？

**Comment by db0010** [comment]
你们解决这个问题了吗，我也是这个问题

**Comment by tunanw** [comment]
我也遇到了这个问题

**Comment by mklzl** [comment]
我抓取的包为啥没有token啊，有没有大佬懂的

**Comment by lyrric** [comment]
> 我抓取的包为啥没有token啊，有没有大佬懂的

你抓取的包是什么样子的？

**Comment by lyrric** [comment]
> 我也遇到了这个问题

我刚试过，程序是正常的

**Comment by mklzl** [comment]
确实正常的，代码没问题，我抓了半天知苗的包，来弄秒苗的



---原始邮件---
发件人: "lyrric"<notifications@github.com&gt;
发送时间: 2021年2月2日(周二) 晚上9:36
收件人: "lyrric/seckill"<seckill@noreply.github.com&gt;;
抄送: "mklzl"<656039120@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [lyrric/seckill] 选择成员这里总是提示登陆超时 (#37)




  
我抓取的包为啥没有token啊，有没有大佬懂的
  
你抓取的包是什么样子的？

**Comment by Claudbbbbb** [comment]
我也是，要疯惹
