### ISSUE TITLE
我们这里小程序不一样

### ISSUE THREAD

**Issue by liuxyon** [lyrric/seckill#38]
我们当地小程序不一样,获取的包类型是这样,看看怎么弄?   

`
GET https://api-ch-dcdn.baobaohehu.com/client/v2/booking_info/booking_data?hospital=5dab1201498b20811f14c57f&checked=checked&id=5dbe52d2561653012ed03b8a&type=baby HTTP/1.1
Host: api-ch-dcdn.baobaohehu.com
Connection: keep-alive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsImlkIjoiNWY4N2Y5NWQ1YmVlMjNmNTI0MzUxYjU3Iiwib3BlbmlkIjoib3RpSnQ1YzlRRlhMTUFhczdFaUJIU3dPN2VIQSIsImlhdCI6MTYwODc5
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 MicroMessenger/7.0.9.501 NetType/WIFI MiniProgramEnv/Windows WindowsWechat
content-type: application/json
Referer: https://servicewechat.com/wx91c7c70ae73b51d6/67/page-frame.html
Accept-Encoding: gzip, deflate, br

`

**Comment by mz0113** [comment]
我好难过，我打开约苗小程序，抓到的都是有赞的技术支持。。。

**Comment by lyrric** [comment]
这个程序，只针对苗苗/约苗，对其他无效
