### ISSUE TITLE
没有疫苗列表选择需要配置什么

### ISSUE THREAD

**Issue by IDEA-Fang** [lyrric/seckill#41]
![image](https://user-images.githubusercontent.com/38692833/105902739-03ae2680-605a-11eb-9085-1139937715a2.png)

**Comment by lyrric** [comment]
默认是成都市，虽然显示的是不是
可以先打开约苗小程序，看看有无疫苗

**Comment by D-xianyu** [comment]
兄弟，怎么运行啊，求教

**Comment by D-xianyu** [comment]
v信号是15281780306，可以的话麻烦大佬教一下，谢谢了哈
