### ISSUE TITLE
tk不是wxapptoken变成了wxtoken，地址也不是miaomiao了，大佬助我！！！

### ISSUE THREAD

**Issue by blf972** [lyrric/seckill#44]
![image](https://user-images.githubusercontent.com/49710410/109851254-6ebccf80-7c8e-11eb-87e1-8d5495b9486c.png)
![image](https://user-images.githubusercontent.com/49710410/109851310-7f6d4580-7c8e-11eb-8ba6-d4ef70241ac9.png)
大佬这个怎么解决

**Comment by blf972** [comment]
我仔细看了一下，好像基本接口都换了，大佬你这边的接口已经被更新了，
![image](https://user-images.githubusercontent.com/49710410/109854970-ac235c00-7c92-11eb-8bdc-151d13f3e878.png)

**Comment by blf972** [comment]
没事了大佬，我搞定了
![image](https://user-images.githubusercontent.com/49710410/109946342-1976d180-7d13-11eb-8878-ee6b00c9eafa.png)

**Comment by wanghang-97** [comment]
> 没事了大佬，我搞定了
> ![image](https://user-images.githubusercontent.com/49710410/109946342-1976d180-7d13-11eb-8878-ee6b00c9eafa.png)

兄弟 你抢到了吗

**Comment by blf972** [comment]
> > 没事了大佬，我搞定了
> > ![image](https://user-images.githubusercontent.com/49710410/109946342-1976d180-7d13-11eb-8878-ee6b00c9eafa.png)
> 
> 兄弟 你抢到了吗

没呢 我在杭州 这两天没苗 还没用过

**Comment by imdreamer2018** [comment]
@blf972 老哥，你把接口都修改了吗？

**Comment by Zz-996633** [comment]
能教教我怎么运行吗？卑微求教

**Comment by blf972** [comment]
> @blf972 老哥，你把接口都修改了吗？

没有没有 用电脑打开小程序成功获取了tk和cookie，用手机也可以

**Comment by LLinVIP** [comment]
> > 能教教我怎么运行吗？卑微求教
> 
> 随便百度一个运行Java程序的教程就好啦

现在好像走云函数了

**Comment by blf972** [comment]
> > > 能教教我怎么运行吗？卑微求教
> > 
> > 
> > 随便百度一个运行Java程序的教程就好啦
> 
> 现在好像走云函数了

没有 我可以正常抓包登录的，昨晚刚打开程序看过没问题

**Comment by mingdongduan** [comment]
兄弟 怎样抓包嘞

**Comment by Totoro-JJ** [comment]
抓不到tk和cookie，地址也变成了cloud.cn2030.com;大佬求教
