### ISSUE TITLE
小程序都走云函数中转了 抓不到cookie和tk怎么破

### ISSUE THREAD

**Issue by NEUAlbertTan** [lyrric/seckill#45]
host都是cloud.cn2030.com 抓不到cookie sad

**Comment by lyrric** [comment]
前几天我才试过没啥问题

**Comment by lyrric** [comment]
你用的什么工具抓的？
如果是fiddler，点击右边的Inspectors，然后点击Raw就可以
如果自动解析有问题，可以自己手动输入cookie和token
ps：要点击解析后再点击确定

**Comment by lyrric** [comment]
这个程序只针对约苗-秒杀小程序使用
