### ISSUE TITLE
Cookie值有六行应该选哪个？/另外就是用户登录已超时

### ISSUE THREAD

**Issue by Cikey97** [lyrric/seckill#47]
Cookie
_xxhm_=%7B%22birthday%22%3A913478400000%2C%22birthdayStr%22%3A%221998-12-13%22%2C%22hasPassword%22%3Afalse%2C%22headerImg%22%3A%22http%3A%2F%2Fthirdwx.qlogo.cn%2Fmmopen%2Fic9BcyRDyOIs9xsQs76BL5ahsPU1N2W7bt8SasdBfgQRnWXHVa0bjXGbecOkaQLptk3JEJey5r1nCXKKeK5YsVUZZasHdxiaA2%2F132%22%2C%22mobile%22%3A%22137****2856%22%2C%22name%22%3A%22%E7%BD%97**%22%2C%22regionCode%22%3A%22330104%22%2C%22sex%22%3A2%2C%22wxSubscribed%22%3A1%7D
_xxhmen_=B5F91AE418ECA6F9ACE844E772B07C34EDB03322AF4B3249BC193808DDF31763BF7E8538EABED6B18EF1D1C9156F9EA733107AF7DAA360954B7C15E258C436807B4E69425D67005FA84E2777340E41CFFA1933CEC9A49B1A9ADBB792B446B6F9F99DF67C4064C49EE043AAB96FC94090ED838CF48FA42B2AFB2970EFCD13842007B720C83D90F80FC2C47786D1ECC9B4459103EBB81E1DC1FF1BC3209A26777775FA83F44BE24E22E50BD9E0F2378901EE87FFD2323F264DA0148873580DBB3277C2AB273768943AA3F250346496E147D88FDDB5EA6318B978A8BD39A7661EA3B56865438A53A069E36DDA2F0C2820BC4ED2F35FE20120BE40731C76E2B0E7F7A65A1F21EA7A489E3D57CF864837CC78111CEC178C996775053BB9FEEC45DA6CD7611DA866DE17E623BAF9222E31FA08EBB6FF39400DB1D5169C0D5DB495106F80796015D98615937855C05E5DE6481DA1E441CB1ACF5860A0A767D0D500CD30BF30B946763985B2E1B85D0E7E5185DECF9D715C3E4B535057A6AD2D0DD25ED85503CF76EB2F9CDBC0DA6D3DB0010230F99BFFAD1ED7F50398DB927A9629D5CA
_xzkj_=wxapptoken:10:2a02b0d8b76662d4a3a730b3b6a7eb58_28e18310a32bad4cd73d901b15e7b2ac
7403=db6b41b11df2d448e7
9557=94c2759b38bd5db9d4
c7c6=238129da724797bc85

点选择成员报错，错误：用户登录超时,请重新登入!，errCode1001

希望大佬能够解答Orz

**Comment by lyrric** [comment]
这里的cookie只是换行了而已，不影响

**Comment by Claudbbbbb** [comment]
我也是，登录超时，怎么搞都不对。

**Comment by ivybs** [comment]
登录超时+1

**Comment by ivybs** [comment]
> 这里的cookie只是换行了而已，不影响

大佬登录超时是为什么呢？辛苦大佬帮忙解答！！

**Comment by JackLengYi** [comment]
卧龙凤雏们，需要你们用抓包工具去抓秒苗上的实时token和cookie，而不是用作者那个写死在程序里的示例demo。。。

**Comment by ivybs** [comment]
> 卧龙凤雏们，需要你们用抓包工具去抓秒苗上的实时token和cookie，而不是用作者那个写死在程序里的示例demo。。。

当然是用抓包工具抓的QAQ demo里面我看是用swing组件获取得输入，然后覆盖的默认写好的tk和cookie 在server/HttpServer.java 141行和144行

**Comment by lyrric** [comment]
> > 卧龙凤雏们，需要你们用抓包工具去抓秒苗上的实时token和cookie，而不是用作者那个写死在程序里的示例demo。。。
> 
> 当然是用抓包工具抓的QAQ demo里面我看是用swing组件获取得输入，然后覆盖的默认写好的tk和cookie 在service/HttpService.java 141行和144行

你用的什么工具抓的？
如果是fiddler，点击右边的Inspectors，然后点击Raw就可以
如果自动解析有问题，可以自己手动输入cookie和token
ps：要点击解析后再点击确定

**Comment by ivybs** [comment]
> > > 卧龙凤雏们，需要你们用抓包工具去抓秒苗上的实时token和cookie，而不是用作者那个写死在程序里的示例demo。。。
> > 
> > 
> > 当然是用抓包工具抓的QAQ demo里面我看是用swing组件获取得输入，然后覆盖的默认写好的tk和cookie 在service/HttpService.java 141行和144行
> 
> 你用的什么工具抓的？
> 如果是fiddler，点击右边的Inspectors，然后点击Raw就可以
> 如果自动解析有问题，可以自己手动输入cookie和token
> ps：要点击解析后再点击确定

用的是fiddler然后手动粘贴进去的，但是没有点解析直接点的确定！下次试试！感谢大佬！

**Comment by lyrric** [comment]
xxhm=%7B%22birthday%22%3%7D; xxhmen=83C0B1A79368C8066460D2993B3C1718; xzkj=wxapptoken:10:e0963da6b3e5d807f5262934c9e503f2

这样，拼成一行，分号;分割
