### ISSUE TITLE
about how to use it?

### ISSUE THREAD

**Issue by huangaszaq** [lyrric/seckill#5]
I'd like to use your program , but I don't know JAVA language or have JAVA IDE. And I may translate your code to Pthon, could you plz give me some help about using or translating?

Thx for your apply!

**Comment by lyrric** [comment]
老哥，会中文不?

**Comment by huangaszaq** [comment]
会啊， 哈哈。简单来说我就是不会java，也没有java IDE，就是想把他搞成python的，我更容易用一点，可能在翻译过程中会有问题向你请教。

**Comment by lyrric** [comment]
哈哈、可以的
造福于人类嘛

**Comment by huangaszaq** [comment]
老哥，加个微信可以吗？

**Comment by lyrric** [comment]
微信就不加了吧，比较隐私
有啥问题直接在这里问，我经常在
