### ISSUE TITLE
抓包 域名已经变成了https://cloud.cn2030.com，有解决办法吗

### ISSUE THREAD

**Issue by ST0new** [lyrric/seckill#50]
GET https://cloud.cn2030.com/sc/wx/HandlerSubscribe.ashx?act=CustomerProduct&id=xxx&lat=34.22259&lng=108.94878 HTTP/1.1
Host: cloud.cn2030.com
Connection: keep-alive
Cookie: ASP.NET_SessionId=lxxxxxxxxxxx
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 MicroMessenger/7.0.9.501 NetType/WIFI MiniProgramEnv/Windows WindowsWechat
content-type: application/json
zftsl: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Referer: https://servicewechat.com/wx2c7f0f3c30d99445/73/page-frame.html
Accept-Encoding: gzip, deflate, br

**Comment by lyrric** [comment]
你用的什么工具抓的？
如果是fiddler，点击右边的Inspectors，然后点击Raw就可以
如果自动解析有问题，可以自己手动输入cookie和token
ps：要点击解析后再点击确定

**Comment by ST0new** [comment]
我遇到得问题是没有抓到下面这个域名
https://miaomiao.scmttec.com
很明显 ，从我放出来得请求包中，没有作者说的cookie 和token。我很意外，是什么原因导致的这种问题。我分析了很久对方客户端。没有遇到作者说的域名和认证机制。

**Comment by ST0new** [comment]
![image](https://user-images.githubusercontent.com/45659593/111242307-dd5c3e80-8639-11eb-906c-f06f1f8837e0.png)

**Comment by ST0new** [comment]
![image](https://user-images.githubusercontent.com/45659593/111242346-efd67800-8639-11eb-89d7-2b8c6da10d05.png)

**Comment by lyrric** [comment]
这个程序只针对约苗-秒杀小程序使用
