### ISSUE TITLE
3个cookie  怎么传

### ISSUE THREAD

**Issue by cccccgithub** [lyrric/seckill#51]
![image](https://user-images.githubusercontent.com/56525471/111272517-b455a100-866d-11eb-982f-317efd630479.png)

**Comment by lyrric** [comment]
_xxhm_=%7B%22birthday%22%3%7D; _xxhmen_=83C0B1A79368C8066460D2993B3C1718; _xzkj_=wxapptoken:10:e0963da6b3e5d807f5262934c9e503f2

这样，拼成一行，冒号分割

**Comment by lyrric** [comment]
_xxhm_=%7B%22birthday%22%3%7D; _xxhmen_=83C0B1A79368C8066460D2993B3C1718; _xzkj_=wxapptoken:10:e0963da6b3e5d807f5262934c9e503f2

这样，拼成一行，冒号分割

**Comment by lyrric** [comment]
说错了，应该是分号;分割
