### ISSUE TITLE
请教一下mac怎么抓包，好像我试了下，全是乱码。

### ISSUE THREAD

**Issue by designer-guo** [lyrric/seckill#53]
token和cookie是抓包获取的吗？

**Comment by lyrric** [comment]
是抓包获取的，没法解答mac相关问题
或者你可以赞助我一台，o(╯□╰)o

**Comment by CoolerTing** [comment]
使用 Charles 抓取，需要安装 https 证书。
参考https://www.cnblogs.com/agang-php/p/10609851.html
