### ISSUE TITLE
java超级小白求助

### ISSUE THREAD

**Issue by Maxmumu** [lyrric/seckill#6]
帮女朋友抢了8-9次，每次都是神仙打架。没学过java，请教大佬怎样使用，如果大佬看到，可以加我qq，1642365931,万分感谢！！！

**Comment by lyrric** [comment]
不会java是小事，添加了release，你可以装一个jdk1.8，然后直接下载sek-kill.jar运行就可以了
但是不会抓小程序的包，就爱莫能助了（百度有很多教程）

**Comment by Maxmumu** [comment]
感谢大佬，用jdk1.8打开了。现在去学抓包

**Comment by wlinnilw** [comment]
> 不会java是小事，添加了release，你可以装一个jdk1.8，然后直接下载sek-kill.jar运行就可以了
> 但是不会抓小程序的包，就爱莫能助了（百度有很多教程）

添加release是怎么操作啊
