### ISSUE TITLE
救救广东省的孩子吧

### ISSUE THREAD

**Issue by HuangWenQuan** [lyrric/seckill#62]
能不能搞一个广东省的脚本

**Comment by lyrric** [comment]
什么意思？

**Comment by HuangWenQuan** [comment]
没有，就你那个约苗的只能抢你们那边的，没能抢广东省这边的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lyrric ***@***.***&gt;
发送时间: 2021年4月27日 11:38
收件人: lyrric/seckill ***@***.***&gt;
抄送: HuangWenQuan ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[lyrric/seckill] 救救广东省的孩子吧 (#62)

**Comment by lyrric** [comment]
广东省那边是通过什么抢的？
