### ISSUE TITLE
有人一直提醒登录状态过期吗？

### ISSUE THREAD

**Issue by zttz789** [lyrric/seckill#66]
我明明是刚抓的tk和cookie，为什么一跑就说我登录过期呀？

**Comment by as1253202091** [comment]
请问一下怎么使用啊

**Comment by lyrric** [comment]
> 我明明是刚抓的tk和cookie，为什么一跑就说我登录过期呀？

如果你是直接填入header，解析后提醒登录过期的话，请尝试手动填入tk和cookie
