### ISSUE TITLE
求助各位大哥！ 我获取到的疫苗列表差一些相关字段 导致程序NullPointException

### ISSUE THREAD

**Issue by Athw** [lyrric/seckill#74]
![Snipaste_2021-06-02_20-02-58](https://user-images.githubusercontent.com/41822960/120476754-8d417c80-c3dd-11eb-959d-a8d9b38a3848.png)
**请求地址我修改成了我能找到的如下：但是没有startTime字段** 我手动给了个时间，现在应该是**获取加密参数st** 这个地址不对   求解答！
`149d
{"code":"0000","data":[{"id":11,"name":"HPV疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/HPV%E7%96%AB%E8%8B%97_1572429923950.png","labels":[{"id":19,"label":"预防宫颈癌","position":2,"isDisplay":1,"catalogId":11}]},{"id":31,"name":"新冠肺炎疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E6%96%B0%E5%86%A0%E8%82%BA%E7%82%8E%E7%96%AB%E8%8B%97_1605748563464.png","labels":[{"id":45,"label":"全民接种","position":2,"isDisplay":1,"catalogId":31},{"id":46,"label":"HOT","position":1,"isDisplay":1,"catalogId":31}]},{"id":13,"name":"乙肝疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E4%B9%99%E8%82%9D%E7%96%AB%E8%8B%97_1572429800893.png","labels":[{"id":21,"label":"预防肝癌","position":2,"isDisplay":1,"catalogId":13}]},{"id":14,"name":"肺炎疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E8%82%BA%E7%82%8E%E7%96%AB%E8%8B%97_1572429710897.png","labels":[{"id":22,"label":"老年人必打","position":2,"isDisplay":1,"catalogId":14}]},{"id":30,"name":"带状疱疹疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E5%B8%A6%E7%8A%B6%E7%96%B1%E7%96%B9%E7%96%AB%E8%8B%97_1591944856126.png","labels":[{"id":43,"label":"1/3发病率","position":2,"isDisplay":1,"catalogId":30},{"id":44,"label":"新","position":1,"isDisplay":1,"catalogId":30}]},{"id":15,"name":"狂犬病疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E7%8B%82%E7%8A%AC%E7%97%85%E7%96%AB%E8%8B%97_1572429614445.png","labels":[{"id":23,"label":"养宠推荐接种","position":2,"isDisplay":1,"catalogId":15}]},{"id":12,"name":"流感疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E6%B5%81%E6%84%9F%E7%96%AB%E8%8B%97_1572429886410.png","labels":[{"id":20,"label":"秋冬保护全家","position":2,"isDisplay":1,"catalogId":12}]},{"id":16,"name":"甲肝疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E7%94%B2%E8%82%9D%E7%96%AB%E8%8B%97_1572429518696.png","labels":[{"id":24,"label":"吃货必打","position":2,"isDisplay":1,"catalogId":16}]},{"id":20,"name":"戊肝疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E6%88%8A%E8%82%9D%E7%96%AB%E8%8B%97_1572428800230.png","labels":[{"id":36,"label":"孕前必备","position":2,"isDisplay":1,"catalogId":20}]},{"id":18,"name":"麻腮风疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E9%BA%BB%E8%85%AE%E9%A3%8E%E7%96%AB%E8%8B%97_1572429285808.png","labels":[{"id":25,"label":"孕前必备","position":2,"isDisplay":1,"catalogId":18}]},{"id":19,"name":"水痘疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E6%B0%B4%E7%97%98%E7%96%AB%E8%8B%97_1572429210470.png","labels":[{"id":28,"label":"成人病死率高","position":2,"isDisplay":1,"catalogId":19}]},{"id":21,"name":"出血热疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E5%87%BA%E8%A1%80%E7%83%AD%E7%96%AB%E8%8B%97_1572428597393.png","labels":[{"id":26,"label":"鼠类传播","position":2,"isDisplay":1,"catalogId":21}]},{"id":22,"name":"黄热病疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E9%BB%84%E7%83%AD%E7%97%85%E7%96%AB%E8%8B%97_1572431005988.png","labels":[{"id":27,"label":"非洲南美必打","position":2,"isDisplay":1,"catalogId":22}]},{"id":23,"name":"流脑疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/ACYW135%E7%BE%A4%E6%B5%81%E8%84%91%E7%96%AB%E8%8B%97_1572428292631.png","labels":[{"id":29,"label":"永久后遗症","position":2,"isDisplay":1,"catalogId":23}]},{"id":24,"name":"乙脑疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E4%B9%99%E8%84%91%E7%96%AB%E8%8B%97_1572428176425.png","labels":[{"id":30,"label":"蚊虫叮咬感染","position":2,"isDisplay":1,"catalogId":24}]},{"id":25,"name":"破伤风疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E7%A0%B4%E4%BC%A4%E9%A3%8E%E7%96%AB%E8%8B%97_1572428038768.png","labels":[{"id":31,"label":"易受伤人群","position":2,"isDisplay":1,"catalogId":25}]},{"id":26,"name":"霍乱疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E9%9C%8D%E4%B9%B1%E7%96%AB%E8%8B%97_1572427883385.png","labels":[{"id":32,"label":"沿海地区高发","position":2,"isDisplay":1,"catalogId":26}]},{"id":27,"name":"伤寒疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E4%BC%A4%E5%AF%92%E7%96%AB%E8%8B%97_1572427714517.png","labels":[{"id":33,"label":"水污染传播","position":2,"isDisplay":1,"catalogId":27}]},{"id":28,"name":"儿童疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E5%84%BF%E7%AB%A5%E7%96%AB%E8%8B%97_1585046779769.png","labels":[{"id":40,"label":"儿童疫苗","position":2,"isDisplay":1,"catalogId":28}]},{"id":29,"name":"其它疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E5%85%B6%E5%AE%83%E7%96%AB%E8%8B%97_1585218451607.png","labels":[{"id":41,"label":"其它疫苗","position":2,"isDisplay":1,"catalogId":29}]}],"ok":true,"notOk":false}
0`

**Comment by AylaAsia-wangxiaodong** [comment]
> ![Snipaste_2021-06-02_20-02-58](https://user-images.githubusercontent.com/41822960/120476754-8d417c80-c3dd-11eb-959d-a8d9b38a3848.png)
> **请求地址我修改成了我能找到的如下：但是没有startTime字段** 我手动给了个时间，现在应该是**获取加密参数st** 这个地址不对 求解答！
> `149d {"code":"0000","data":[{"id":11,"name":"HPV疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/HPV%E7%96%AB%E8%8B%97_1572429923950.png","labels":[{"id":19,"label":"预防宫颈癌","position":2,"isDisplay":1,"catalogId":11}]},{"id":31,"name":"新冠肺炎疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E6%96%B0%E5%86%A0%E8%82%BA%E7%82%8E%E7%96%AB%E8%8B%97_1605748563464.png","labels":[{"id":45,"label":"全民接种","position":2,"isDisplay":1,"catalogId":31},{"id":46,"label":"HOT","position":1,"isDisplay":1,"catalogId":31}]},{"id":13,"name":"乙肝疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E4%B9%99%E8%82%9D%E7%96%AB%E8%8B%97_1572429800893.png","labels":[{"id":21,"label":"预防肝癌","position":2,"isDisplay":1,"catalogId":13}]},{"id":14,"name":"肺炎疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E8%82%BA%E7%82%8E%E7%96%AB%E8%8B%97_1572429710897.png","labels":[{"id":22,"label":"老年人必打","position":2,"isDisplay":1,"catalogId":14}]},{"id":30,"name":"带状疱疹疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E5%B8%A6%E7%8A%B6%E7%96%B1%E7%96%B9%E7%96%AB%E8%8B%97_1591944856126.png","labels":[{"id":43,"label":"1/3发病率","position":2,"isDisplay":1,"catalogId":30},{"id":44,"label":"新","position":1,"isDisplay":1,"catalogId":30}]},{"id":15,"name":"狂犬病疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E7%8B%82%E7%8A%AC%E7%97%85%E7%96%AB%E8%8B%97_1572429614445.png","labels":[{"id":23,"label":"养宠推荐接种","position":2,"isDisplay":1,"catalogId":15}]},{"id":12,"name":"流感疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E6%B5%81%E6%84%9F%E7%96%AB%E8%8B%97_1572429886410.png","labels":[{"id":20,"label":"秋冬保护全家","position":2,"isDisplay":1,"catalogId":12}]},{"id":16,"name":"甲肝疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E7%94%B2%E8%82%9D%E7%96%AB%E8%8B%97_1572429518696.png","labels":[{"id":24,"label":"吃货必打","position":2,"isDisplay":1,"catalogId":16}]},{"id":20,"name":"戊肝疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E6%88%8A%E8%82%9D%E7%96%AB%E8%8B%97_1572428800230.png","labels":[{"id":36,"label":"孕前必备","position":2,"isDisplay":1,"catalogId":20}]},{"id":18,"name":"麻腮风疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E9%BA%BB%E8%85%AE%E9%A3%8E%E7%96%AB%E8%8B%97_1572429285808.png","labels":[{"id":25,"label":"孕前必备","position":2,"isDisplay":1,"catalogId":18}]},{"id":19,"name":"水痘疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E6%B0%B4%E7%97%98%E7%96%AB%E8%8B%97_1572429210470.png","labels":[{"id":28,"label":"成人病死率高","position":2,"isDisplay":1,"catalogId":19}]},{"id":21,"name":"出血热疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E5%87%BA%E8%A1%80%E7%83%AD%E7%96%AB%E8%8B%97_1572428597393.png","labels":[{"id":26,"label":"鼠类传播","position":2,"isDisplay":1,"catalogId":21}]},{"id":22,"name":"黄热病疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E9%BB%84%E7%83%AD%E7%97%85%E7%96%AB%E8%8B%97_1572431005988.png","labels":[{"id":27,"label":"非洲南美必打","position":2,"isDisplay":1,"catalogId":22}]},{"id":23,"name":"流脑疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/ACYW135%E7%BE%A4%E6%B5%81%E8%84%91%E7%96%AB%E8%8B%97_1572428292631.png","labels":[{"id":29,"label":"永久后遗症","position":2,"isDisplay":1,"catalogId":23}]},{"id":24,"name":"乙脑疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E4%B9%99%E8%84%91%E7%96%AB%E8%8B%97_1572428176425.png","labels":[{"id":30,"label":"蚊虫叮咬感染","position":2,"isDisplay":1,"catalogId":24}]},{"id":25,"name":"破伤风疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E7%A0%B4%E4%BC%A4%E9%A3%8E%E7%96%AB%E8%8B%97_1572428038768.png","labels":[{"id":31,"label":"易受伤人群","position":2,"isDisplay":1,"catalogId":25}]},{"id":26,"name":"霍乱疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E9%9C%8D%E4%B9%B1%E7%96%AB%E8%8B%97_1572427883385.png","labels":[{"id":32,"label":"沿海地区高发","position":2,"isDisplay":1,"catalogId":26}]},{"id":27,"name":"伤寒疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E4%BC%A4%E5%AF%92%E7%96%AB%E8%8B%97_1572427714517.png","labels":[{"id":33,"label":"水污染传播","position":2,"isDisplay":1,"catalogId":27}]},{"id":28,"name":"儿童疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E5%84%BF%E7%AB%A5%E7%96%AB%E8%8B%97_1585046779769.png","labels":[{"id":40,"label":"儿童疫苗","position":2,"isDisplay":1,"catalogId":28}]},{"id":29,"name":"其它疫苗","iconUrl":"https://adultvacc-1253522668.file.myqcloud.com/thematic%20pic/%E5%85%B6%E5%AE%83%E7%96%AB%E8%8B%97_1585218451607.png","labels":[{"id":41,"label":"其它疫苗","position":2,"isDisplay":1,"catalogId":29}]}],"ok":true,"notOk":false} 0`

这个工具是针对约苗得秒苗小程序，其它是无法工作的
