### ISSUE TITLE
java执行时提示没有主清单属性

### ISSUE THREAD

**Issue by clearlovexx** [lyrric/seckill#8]
下载release后，使用java命令执行.jar文件，报错提示没有主清单属性

> G:\download\seckill-1.0\release>java -jar sec-kill.jar 
sec-kill.jar中没有主清单属性

**Comment by clearlovexx** [comment]
抱歉没看到已经有解决了，早上打开的没刷新

**Comment by clearlovexx** [comment]
请问是否没有更改v1.0的jar包，重新下载的依然是提示没有主清单属性

**Comment by lyrric** [comment]
稍等，我检查下

**Comment by lyrric** [comment]
> 请问是否没有更改v1.0的jar包，重新下载的依然是提示没有主清单属性
你确定是从这个地址下载的？
我试过，没有任何问题
https://github.com/lyrric/seckill/releases/tag/V1.0

**Comment by lyrric** [comment]
> 请问是否没有更改v1.0的jar包，重新下载的依然是提示没有主清单属性

你确定是从这个地址下载的？
我试过，没有任何问题
https://github.com/lyrric/seckill/releases/tag/V1.0

**Comment by clearlovexx** [comment]
可能是下到源码去了，我重新下载试试

**Comment by clearlovexx** [comment]
测试可以了，谢谢
