### ISSUE TITLE
Fd抓包问题

### ISSUE THREAD

**Issue by Maxmumu** [lyrric/seckill#9]
我登录电脑版微信，打开手机分享的小程序，fd抓到了包，如图，但解析不出来。求助大佬
（这一场是明天 8.12 上午9点的）
![抓包](https://user-images.githubusercontent.com/47938014/89877200-556d0c80-dbf2-11ea-968f-2d11cea20a40.png)
![结果](https://user-images.githubusercontent.com/47938014/89877215-5a31c080-dbf2-11ea-8a54-7f62f2ad35aa.png)

**Comment by clearlovexx** [comment]
手动复制对应的tk和Cookie，复制好了保存就行

**Comment by lyrric** [comment]
格式不一致导致的，这个是小问题，手动复制对应的tk和Cookie，就行
解析只是为了方便调试用的，写的比较傻瓜式（tk的下一行必须是cookie，cookie 的下一行必须是charset）
后期有时间，再优化一下解析算法

**Comment by Maxmumu** [comment]
> 格式不一致导致的，这个是小问题，手动复制对应的tk和Cookie，就行
> 解析只是为了方便调试用的，写的比较傻瓜式（tk的下一行必须是cookie，cookie 的下一行必须是charset）
> 后期有时间，再优化一下解析算法

调好了，我用fd抓的微信电脑版的包，打开小程序的时候有3个相关包，只有一个带有tk数据，我就用了这个。
复制以后，没解析成功，不过相应数据都出来了，但是 开始 按钮是灰色的，是到点才能点击开始吗，如下图
![1](https://user-images.githubusercontent.com/47938014/89887003-265d9780-dc00-11ea-9c71-69e98f20b246.png)
![2](https://user-images.githubusercontent.com/47938014/89887009-29f11e80-dc00-11ea-8311-05cbfc86d4fa.png)
![3](https://user-images.githubusercontent.com/47938014/89887024-2f4e6900-dc00-11ea-80bb-722b9bd2027c.png)

**Comment by lyrric** [comment]
> > 格式不一致导致的，这个是小问题，手动复制对应的tk和Cookie，就行
> > 解析只是为了方便调试用的，写的比较傻瓜式（tk的下一行必须是cookie，cookie 的下一行必须是charset）
> > 后期有时间，再优化一下解析算法
> 
> 调好了，我用fd抓的微信电脑版的包，打开小程序的时候有3个相关包，只有一个带有tk数据，我就用了这个。
> 复制以后，没解析成功，不过相应数据都出来了，但是 开始 按钮是灰色的，是到点才能点击开始吗，如下图
> ![1](https://user-images.githubusercontent.com/47938014/89887003-265d9780-dc00-11ea-9c71-69e98f20b246.png)
> ![2](https://user-images.githubusercontent.com/47938014/89887009-29f11e80-dc00-11ea-8311-05cbfc86d4fa.png)
> ![3](https://user-images.githubusercontent.com/47938014/89887024-2f4e6900-dc00-11ea-80bb-722b9bd2027c.png)

开始按钮只有在点击了之后才会变成灰色，你是不是之前点过了？

**Comment by Maxmumu** [comment]
> > > 格式不一致导致的，这个是小问题，手动复制对应的tk和Cookie，就行
> > > 解析只是为了方便调试用的，写的比较傻瓜式（tk的下一行必须是cookie，cookie 的下一行必须是charset）
> > > 后期有时间，再优化一下解析算法
> > 
> > 
> > 调好了，我用fd抓的微信电脑版的包，打开小程序的时候有3个相关包，只有一个带有tk数据，我就用了这个。
> > 复制以后，没解析成功，不过相应数据都出来了，但是 开始 按钮是灰色的，是到点才能点击开始吗，如下图
> > ![1](https://user-images.githubusercontent.com/47938014/89887003-265d9780-dc00-11ea-9c71-69e98f20b246.png)
> > ![2](https://user-images.githubusercontent.com/47938014/89887009-29f11e80-dc00-11ea-8311-05cbfc86d4fa.png)
> > ![3](https://user-images.githubusercontent.com/47938014/89887024-2f4e6900-dc00-11ea-80bb-722b9bd2027c.png)
> 
> 开始按钮只有在点击了之后才会变成灰色，你是不是之前点过了？

发现了，我后面重新试了，一切正常。
大佬可以把 万能解析 的版本放在release吗

**Comment by lyrric** [comment]
下一版会加入控制台方式的时候再加入release
